name: Build Pillager

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install NuGet Packages
      run: nuget restore Pillager.sln
      
    - name: Build solution
      run: msbuild -nologo -v:m -p:Configuration=${{ matrix.configuration }} Pillager.sln
      
    
    - name: Install 7Zip PowerShell Module
      shell: powershell
      run: Install-Module 7Zip4PowerShell -Force -Verbose


    # 使用 actions/upload-artifact 上传构建产物
    - name: Upload Pillager.exe
      uses: actions/upload-artifact@v3
      with:
        name: Pillager.exe
        path: ./Pillager/bin/Release/Pillager.exe

    - name: Upload Pillager.bin
      uses: actions/upload-artifact@v3
      with:
        name: Pillager.bin
        path: ./Pillager.bin

    - name: Upload cs-plugin.zip
      uses: actions/upload-artifact@v3
      with:
        name: cs-plugin.zip
        path: ./cs-plugin.zip
