name: Build Pillager

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0
    
    - name: Checkout private donut
      uses: actions/checkout@v3
      with:
        repository: qwqdanchun/donut-self
        token: ${{ secrets.PERSONAL_TOKEN }}
        path: donut

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install NuGet Packages
      run: nuget restore Pillager.sln
      
    - name: Build solution
      run: msbuild -nologo -v:m -p:Configuration=${{ matrix.configuration }} Pillager.sln
      
    - name: Build Shellcode
      shell: powershell
      run: .\donut\donut.exe -z 3 -i .\Pillager\bin\Release\Pillager.exe -o .\Pillager.bin
      
    - name: Install 7Zip PowerShell Module
      shell: powershell
      run: Install-Module 7Zip4PowerShell -Force -Verbose

    - name: Copy Pillager.bin
      run: copy .\Pillager.bin .\cs-plugin\module\Pillager.bin

    - name: Pack Plugin Folder
      shell: powershell
      run: Compress-7Zip "cs-plugin" -ArchiveFileName "cs-plugin.zip" -Format Zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Pillager-artifacts
        path: |
          ./Pillager/bin/Release/Pillager.exe
          ./Pillager.bin
          ./cs-plugin.zip
